services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clean_shop
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  mongodb_data:
  postgres_data:
